import numpy as np

# ---------------------------------------------------------------------------
# Simulation-mode script generator
# All generated scripts drive the robot model directly via robot.set_joint_value()
# and robot.inverse_kinematics() — no serial port required.
# ---------------------------------------------------------------------------

def generate_python_script(robot):
    """Generates a simulation Python script using the E-labs Robot API."""
    joint_names = list(robot.joints.keys())
    first = joint_names[0] if joint_names else 'Joint1'

    # Build joint limits info for comments
    limits_lines = []
    for name in joint_names:
        j = robot.joints[name]
        limits_lines.append(
            f"#   {name:20s}  min={j.min_limit:+7.1f}°  max={j.max_limit:+7.1f}°"
        )
    limits_block = "\n".join(limits_lines)

    code = f"""# ============================================================
# E-labs Simulation Script  (Python)
# Auto-generated by ToRoTRoN Script Generator
# This script controls the 3D robot simulation directly.
# No serial port or hardware required.
# ============================================================

import time
import numpy as np

# ----- Joint names detected from your robot -----
JOINTS = {joint_names}

# ----- Joint limits (for reference) -----
{limits_block}

# ----------------------------------------------------------------
# SimRobot — thin wrapper around the E-labs Robot object.
# When running INSIDE the E-lab app, pass the live `robot` object.
# ----------------------------------------------------------------
class SimRobot:
    def __init__(self, robot):
        self.robot = robot

    # --- Joint-space control ---
    def move(self, joint_name, angle_deg, delay=0.02):
        \"\"\"Move a single joint to angle_deg (degrees).\"\"\"
        ok = self.robot.set_joint_value(joint_name, angle_deg)
        if not ok:
            print(f"[WARN] Joint '{{joint_name}}' not found.")
        time.sleep(delay)

    def move_all(self, angles_dict, delay=0.02):
        \"\"\"Move multiple joints at once. Dict: {{joint_name: angle}}.\"\"\"
        for name, angle in angles_dict.items():
            self.robot.set_joint_value(name, angle)
        time.sleep(delay)

    def home(self, delay=0.5):
        \"\"\"Reset all joints to 0°.\\"\"\"
        for name in JOINTS:
            self.robot.set_joint_value(name, 0.0)
        time.sleep(delay)

    # --- Cartesian / IK control ---
    def move_to_xyz(self, x, y, z, tcp_link, delay=0.05):
        \"\"\"Move TCP to world position [x, y, z] using IK.\"\"\"
        success = self.robot.inverse_kinematics(
            target_pos=[x, y, z],
            tcp_link=tcp_link,
            tolerance=0.5,
        )
        if not success:
            print(f"[WARN] IK failed for target ({{x:.2f}}, {{y:.2f}}, {{z:.2f}})")
        time.sleep(delay)

    # --- Gripper ---
    def gripper_open(self, gripper_joint=None, delay=0.3):
        \"\"\"Open gripper (set to max limit).\"\"\"
        name = gripper_joint or (JOINTS[-1] if JOINTS else None)
        if name and name in self.robot.joints:
            self.robot.set_joint_value(name, self.robot.joints[name].max_limit)
        time.sleep(delay)

    def gripper_close(self, gripper_joint=None, delay=0.3):
        \"\"\"Close gripper (set to 0°).\\"\"\"
        name = gripper_joint or (JOINTS[-1] if JOINTS else None)
        if name and name in self.robot.joints:
            self.robot.set_joint_value(name, 0.0)
        time.sleep(delay)


# ============================================================
# MOTION SEQUENCES  —  edit these to create your own programs
# ============================================================

def pick_and_place(sim):
    \"\"\"Pick-and-place sequence using joint-space waypoints.\"\"\"
    print("--- Pick and Place ---")

    # 1. Home
    sim.home()

    # 2. Move above pick position
    sim.move_all({{
        '{first}': 45,
    }})

    # 3. Descend to pick
    sim.move_all({{
        '{first}': 45,
    }})
    sim.gripper_close()

    # 4. Lift
    sim.move_all({{
        '{first}': 30,
    }})

    # 5. Move to place position
    sim.move_all({{
        '{first}': -45,
    }})

    # 6. Release
    sim.gripper_open()

    # 7. Return home
    sim.home()
    print("--- Pick and Place Complete ---")


def draw_square(sim):
    \"\"\"Trace a square using joint-space waypoints.\"\"\"
    print("--- Drawing Square ---")
    corners = [
        {{'{first}': 30}},
        {{'{first}': 30}},
        {{'{first}': -30}},
        {{'{first}': -30}},
        {{'{first}': 30}},   # close path
    ]
    for wp in corners:
        sim.move_all(wp, delay=0.3)
    print("--- Square Complete ---")


def draw_circle(sim, steps=36):
    \"\"\"Sweep in a circular arc through joint space.\"\"\"
    print("--- Drawing Circle ---")
    center, radius = 0.0, 30.0
    for i in range(steps + 1):
        theta = 2 * np.pi * i / steps
        angle = center + radius * np.cos(theta)
        sim.move('{first}', angle, delay=0.02)
    print("--- Circle Complete ---")


# ============================================================
# ENTRY POINT
# When running inside E-lab, `robot` is injected automatically.
# ============================================================
def run(robot):
    sim = SimRobot(robot)

    # Choose which sequence to run:
    pick_and_place(sim)
    # draw_square(sim)
    # draw_circle(sim)
"""
    return code


def generate_matlab_script(robot):
    """Generates a simulation MATLAB script using E-labs Robot API notation."""
    joint_names = list(robot.joints.keys())
    first = joint_names[0] if joint_names else 'Joint1'

    limits_lines = []
    for name in joint_names:
        j = robot.joints[name]
        limits_lines.append(
            f"%   {name:20s}  min={j.min_limit:+7.1f} deg  max={j.max_limit:+7.1f} deg"
        )
    limits_block = "\n".join(limits_lines)

    joints_cell = "{" + ", ".join(f"'{n}'" for n in joint_names) + "}"

    code = f"""% ============================================================
% E-labs Simulation Script  (MATLAB / Octave)
% Auto-generated by ToRoTRoN Script Generator
% Controls the 3D robot simulation — no hardware required.
% ============================================================

% Joint names detected from your robot:
joints = {joints_cell};

% Joint limits (for reference):
{limits_block}

% ----------------------------------------------------------------
% Helper: call E-labs Python robot API from MATLAB via py.*
% If you are running inside E-labs, use the robot object directly.
% ----------------------------------------------------------------

function sim_move(robot, joint_name, angle_deg, delay_s)
    if nargin < 4, delay_s = 0.02; end
    robot.set_joint_value(joint_name, angle_deg);
    pause(delay_s);
end

function sim_home(robot, joints, delay_s)
    if nargin < 3, delay_s = 0.5; end
    for i = 1:length(joints)
        robot.set_joint_value(joints{{i}}, 0);
    end
    pause(delay_s);
end

function gripper_open(robot, joint_name, delay_s)
    if nargin < 3, delay_s = 0.3; end
    j = robot.joints{{joint_name}};
    robot.set_joint_value(joint_name, j.max_limit);
    pause(delay_s);
end

function gripper_close(robot, joint_name, delay_s)
    if nargin < 3, delay_s = 0.3; end
    robot.set_joint_value(joint_name, 0);
    pause(delay_s);
end

% ============================================================
% PICK AND PLACE SEQUENCE
% ============================================================
function pick_and_place(robot, joints)
    fprintf('--- Pick and Place ---\\n');

    sim_home(robot, joints);

    % Move to pick position
    sim_move(robot, '{first}', 45, 0.3);
    gripper_close(robot, '{first}');

    % Lift
    sim_move(robot, '{first}', 30, 0.3);

    % Move to place
    sim_move(robot, '{first}', -45, 0.3);
    gripper_open(robot, '{first}');

    sim_home(robot, joints);
    fprintf('--- Pick and Place Complete ---\\n');
end

% ============================================================
% DRAW A SQUARE (joint-space waypoints)
% ============================================================
function draw_square(robot)
    fprintf('--- Drawing Square ---\\n');
    corners = [30, -30, -30, 30, 30];   % Joint1 angles
    for i = 1:length(corners)
        sim_move(robot, '{first}', corners(i), 0.3);
    end
    fprintf('--- Square Complete ---\\n');
end

% ============================================================
% DRAW A CIRCLE (parametric sweep)
% ============================================================
function draw_circle(robot, steps)
    if nargin < 2, steps = 36; end
    fprintf('--- Drawing Circle ---\\n');
    center = 0; radius = 30;
    for i = 0:steps
        theta = 2 * pi * i / steps;
        angle = center + radius * cos(theta);
        sim_move(robot, '{first}', angle, 0.02);
    end
    fprintf('--- Circle Complete ---\\n');
end

% ============================================================
% ENTRY POINT — uncomment the sequence you want to run
% ============================================================
% pick_and_place(robot, joints);
% draw_square(robot);
% draw_circle(robot, 36);
"""
    return code
